version: '3'


services: 

    mysql-dev:
        image: mysql:latest
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: expressdb
        ports: 
          - "3308:3306"
        volumes: 
          - "./my.conf:/etc/mysql/conf.d/config-file.cnf"
          - "./data:/var/lib/mysql:rw"
    

    mysql-legacy:
        image: mysql:5.7
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: legacyapp
        ports: 
          - "3309:3306"
        
    admin:
        image: adminer
        ports: 
          - 8080:8080  

    #client:
    #    image: mysql:latest
    #   depends_on: 
     #       - mysql-dev
      #  command: mysql -uroot -proot -hmysql-dev expressdb
